name: sub

on:
  push:
    branches: [ sub ]
  pull_request:
    branches: [ sub ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test script
        run: echo Hello world from ${{ github.ref }}!
