name: stable/cm-13.0-ZNH5Y+dt2w

on:
  push:
    branches: [ stable/cm-13.0-ZNH5Y+dt2w ]
  pull_request:
    branches: [ stable/cm-13.0-ZNH5Y+dt2w ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test script
        run: echo Hello world from ${{ github.ref }}!
